-- 程序数据库初始化脚本
-- 2016-03-15

--
-- 创建应用信息表 ( apps ) --

CREATE TABLE IF NOT EXISTS PUBLIC.APPS
(ID IDENTITY NOT NULL,
NAME VARCHAR(45) NOT NULL,
VERSION VARCHAR(25) NOT NULL,
UPDATETIME TIMESTAMP,
CREATETIME TIMESTAMP NOT NULL,
STATUS TINYINT NOT NULL,
PLATFORM TINYINT NOT NULL,
BUNDLEIDENTIFIER VARCHAR(200) NOT NULL,
PRIMARY KEY (ID));

--
-- 创建用户表 ( users ) --

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(ID IDENTITY NOT NULL,
MOBILE VARCHAR(45) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
UPDATETIME TIMESTAMP,
CREATETIME TIMESTAMP NOT NULL,
STATUS TINYINT NOT NULL,
ROLE TINYINT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (MOBILE));

--
-- 数据库升级脚本
ALTER TABLE PUBLIC.APPS DROP COLUMN IF EXISTS SMALLIMAGEURL;
ALTER TABLE PUBLIC.APPS DROP COLUMN IF EXISTS LARGEIMAGEURL;